spring:
  application:
    name: gray-zuul

server:
  address: 0.0.0.0
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9079/eureka/
  instance:
    prefer-ip-address: true
config:
  serverName: gray-zuul

logging:
  level:
    cn.woodwhales: debug