spring:
  application:
    name: gray-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true

server:
  address: 0.0.0.0
  port: 9086

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9079/eureka/
  instance:
    prefer-ip-address: true
config:
  serverName: ${spring.application.name}

logging:
  level:
    cn.woodwhales: debug