spring:
  profiles:
    active: dev
  autoconfigure:
    exclude: org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration,org.springframework.cloud.client.serviceregistry.AutoServiceRegistrationAutoConfiguration
  application:
    name: gray-nacos
  cloud:
    nacos:
      # Nacos作为配置中心地址
      config:
        server-addr: 127.0.0.1:8848
        # 指定yaml格式的配置
        file-extension: yml
        extension-configs:
          - data-id: ${spring.application.name}
            group: DEFAULT_GROUP
            refresh: true


server:
  address: 0.0.0.0
  port: 9087

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9079/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      gray-tag: v2
config:
  serverName: ${spring.application.name}-new
  grayTag: v2-dev

logging:
  level:
    cn.woodwhales: debug